name: 'extract-major-beta-version'
description: 'Return the current _major beta version_. Fails if no beta could be found.'
inputs:
  token:
    description: "Github auth token"
    default: ${{ github.token }}
outputs:
  beta_version:
    description: "The last major version of a beta release (like 88)."
runs:
  using: 'docker'
  image: 'Dockerfile'
